name: flutter_candlesticks
description: Elegant OHLC Candlestick and Trade Volume charts for Flutter.
version: 0.1.4
homepage: https://github.com/trentpiercy/flutter-candlesticks

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  k_chart: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'